//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunNetworkDisk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filedate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filedate()
        {
            this.Share = new HashSet<Share>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string MD5Name { get; set; }
        public string Type { get; set; }
        public long FatherFolder { get; set; }
        public double Size { get; set; }
        public string FullPath { get; set; }
        public string RelativePath { get; set; }
        public string Date { get; set; }
    
        public virtual Floder Floder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Share> Share { get; set; }
    }
}
