//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunNetworkDisk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public long ID { get; set; }
        public long FileID { get; set; }
        public long Type { get; set; }
        public string ShareCode { get; set; }
        public string Path { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    
        public virtual Filedate Filedate { get; set; }
    }
}
